    <div class="bas">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d818.1967589419288!2d2.3433365361422993!3d48.861599105973!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e221fa7599d%3A0x467ef2313eb469ac!2s64%20Rue%20Saint-Honor%C3%A9%2C%2075001%20Paris!5e0!3m2!1sfr!2sfr!4v1710509392087!5m2!1sfr!2sfr" height="200"></iframe>
        <p>
            Siège social
            <br>
            <br>64 Rue Saint-Honoré
            <br>
            <br>Paris (75001)
            <br>
            <br>France métropolitaine
        </p>
    </div>
    <div class="bas">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Atque voluptate omnis expedita necessitatibus recusandae, laboriosam harum saepe ad quia porro repellat facilis modi illo, ducimus eaque odio quos repudiandae earum. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quasi, culpa porro maiores quam alias architecto laboriosam quas ea impedit, consequuntur, magnam illo ab fugiat distinctio quis voluptates odio ipsa et. Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut, cupiditate ducimus natus et unde aliquid perferendis iusto ullam assumenda expedita! Deleniti nesciunt veritatis, repellat incidunt libero labore odio officiis pariatur!</p>
    </div>
    <footer>
        <p>&copy; Copyright 2024</p>
    </footer>
    <script type="text/javascript" src="<?= ROOT ?>scripts/menu.js"></script>
</body>
</html>